
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: kipek/docker_lab:v1
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    container_name: redis-prod
    volumes:
      - "./redis-data:/data"